### ISSUE TITLE
is the secrets path hard-coded in the webapp?

### ISSUE THREAD

**Issue by todd-dsm** [hashicorp/vault-client-go#266]
## Question

_**Does the simple-vault-client have the path secret/data/webapp/config hard-coded?**_ 

Follow up: _**Could the test client be made to consume the path assigned to `VAULT_SECRET_PATH`?**_

## Details

I'm testing with the hashieducation/simple-vault-client:latest; everything seems to work fine. However, I've changed the name from `webapp` to `foo` and namespace from `demo` to `bar` AND

Added a `VAULT_SECRET_PATH=secret/data/foo/config`:

```yaml
...
    spec:
      serviceAccountName: foo-sa
      containers:
        - name: app
          image: hashieducation/simple-vault-client:latest
          imagePullPolicy: Always
          env:
            - name: VAULT_SECRET_PATH
              value: 'secret/data/foo/config'
            - name: VAULT_ADDR
              value: 'http://vault.vault.svc:8200'
            - name: JWT_PATH
              value: '/var/run/secrets/kubernetes.io/serviceaccount/token'
            - name: SERVICE_PORT
              value: '8080'
```

but the client is still trying to access `secret/data/webapp/config`.

## Link to the Vault API Docs that support this feature

The Vault Docs URL

The instructions are [here](https://developer.hashicorp.com/vault/tutorials/kubernetes/kubernetes-minikube-raft#launch-a-web-application). 

## Additional context

I've checked a few different resources and the all list the same kv path: `secret/data/webapp/config`.
